---
- name: Perform packages update
  include_tasks: update.yml
  when: sysprep_install_updates | bool

- name: Install base applications
  include_tasks: base_apps.yml

- name: Change shell for users
  user:
    name: "{{ item }}"
    shell: "/usr/bin/zsh"
  loop: "{{ users }}"
