---
- name: Add Google Chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome repo file
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Add apt key for Typora
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BA300B7755AFCFAE

- name: Add Typora repo
  apt_repository:
    repo: deb https://typora.io/linux ./
    state: present
    filename: typora

- name: Add MS VS Code key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /usr/share/keyrings/packages.microsoft.gpg

- name: Add MS VS Code repo file
  apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg]
      https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Add Atom key
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- name: Add Atom repo file
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
    filename: atom

- name: Add Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo file
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker

- name: Add ansible repo file
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    filename: ansible

- name: Install applications
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - telegram-desktop
    - typora
    - google-chrome-stable
    - code
    - atom
    - docker-ce
    - ansible

- name: Add user to group docker
  user:
    name: "{{ i3wm_user }}"
    groups: docker
    append: yes
