---
- name: Copy Google Chrome repo file
  copy:
    src: google-chrome.list
    dest: "{{ google_chrom_apt_file }}"
    owner: root
    group: root
    mode: 0644
  register: google_chrome_apt_file_result

- name: Add Google Chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  args:
    warn: false
  when: google_chrome_apt_file_result.changed

- name: Update apt cache
  apt:
    update_cache: yes
  when: google_chrome_apt_file_result.changed

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present

- name: Add apt key for Typora
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BA300B7755AFCFAE

- name: Add Typora repo
  apt_repository:
    repo: deb https://typora.io/linux ./
    state: present
    filename: typora

- name: Install Typora
  apt:
    name: typora
    state: present

